In [9]:
"""This Notebook will run through the fundamentals of data analysis tools.
   From series and dataframes to basics in data analysis in Pandas and Seaborn. """

'This Notebook will run through the fundamentals of data analysis tools.\n   From series and dataframes to basics in data analysis in Pandas and Seaborn. '

In [10]:
#Following will be basic data types which will be ever present, and their common methods

In [11]:
my_list = ['a','b','c']

In [12]:
print(my_list)

['a', 'b', 'c']


In [13]:
my_list.append('New')

In [14]:
my_list.append(['d','e','f'])

In [15]:
my_list[4][1]

'e'

In [16]:
dict = {'key1':{'innerkey1':[0,1,2]}}

In [17]:
dict['key1']['innerkey1'][2]

2

In [18]:
dict['key1'] = [1,2,3]

In [19]:
dict['key2'] = [4,5,6]

In [20]:
if 1>2:
    print('wrong!')
else:
    print('learn better syntax')

learn better syntax


In [21]:
def times2(var):
    return var*2

In [22]:
seq = [1,2,3,4,5]

for num in seq:
    print(times2(num))

2
4
6
8
10


In [23]:
list(map(lambda num: num*3,seq))

[3, 6, 9, 12, 15]

In [24]:
list(filter(lambda num: num%2 == 0, seq))

[2, 4]

In [25]:
import numpy as np

In [26]:
#This will be followed by numpy excercises and notes 
my_list = [1,2,3]

np.array(my_list)



array([1, 2, 3])

In [27]:
arr = np.array(my_list)
print(arr)

[1 2 3]


In [28]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]] # A matrice is reperesented as a list of lists

In [29]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
#Generating lists can be done quickly with numpy

np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
np.zeros(3)

array([0., 0., 0.])

In [32]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [33]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [34]:
np.linspace(0,11,5) #Generates arrays filled with a number of evenly spaced values within a range

array([ 0.  ,  2.75,  5.5 ,  8.25, 11.  ])

In [35]:
np.random.rand(5)

array([0.20214204, 0.14255444, 0.96245941, 0.13944578, 0.60233788])

In [36]:
np.random.rand(5,5)

array([[0.45528286, 0.24969377, 0.53667087, 0.01319274, 0.97534464],
       [0.30246727, 0.25076333, 0.89148547, 0.44520725, 0.40696756],
       [0.77694705, 0.52989148, 0.90147434, 0.64520583, 0.45498068],
       [0.83954026, 0.07989256, 0.78146018, 0.40462547, 0.45975204],
       [0.86371253, 0.52299352, 0.62447737, 0.45946296, 0.880114  ]])

In [37]:
np.random.randn(5) # Gaussian distribution around 0

array([-0.43243175,  0.12227948,  0.00639175,  0.20060057, -0.70580571])

In [38]:
arr = np.random.randint(1,100,10) #10 random integers between 1(incl) and 100(excl)

In [39]:
arr.max()

93

In [40]:
arr.argmax()

8

In [41]:
# what follows are notes and examples of numpy indexing and selection.

In [42]:
arr = np.arange(1,11)

In [43]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
arr[0:6]

array([1, 2, 3, 4, 5, 6])

In [45]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [46]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [47]:
arr_2d[:3,1:2]

array([[10],
       [25],
       [40]])

In [48]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [50]:
bool_arr = arr > 5

In [51]:
#Following will be Pandas basics from series to dataframes

In [52]:
import numpy as np
import pandas as pd

In [53]:
labels = ['a','b','c']
my_data = [10,20,30]
arr = np.array(my_data)
dic = {'a':10,'b':20,'c':30}

In [54]:
pd.Series(data=my_data, index=labels)

a    10
b    20
c    30
dtype: int64

In [55]:
#Raw lists can be used to create pandas series along with numpy arrays as well.
pd.Series(arr,labels)

a    10
b    20
c    30
dtype: int32

In [56]:
"""Note that passing in a dictionary will have the keys be assigned as indices
    and the values will be assigned as data."""

pd.Series(dic)

a    10
b    20
c    30
dtype: int64

In [57]:
# Series, just like a dictionary, make it easier to look up information more precisely.
# Following is an example

In [58]:
ser1 = pd.Series([1,2,3,4], ['USA','GERMANY','USSR','JAPAN'])
ser1

USA        1
GERMANY    2
USSR       3
JAPAN      4
dtype: int64

In [59]:
ser2 = pd.Series([1,2,5,4], ['USA','GERMANY','ITALY','JAPAN'])
ser2

USA        1
GERMANY    2
ITALY      5
JAPAN      4
dtype: int64

In [60]:
#Grabbing information is similar to indexing

ser1['USA']

1

In [61]:
"""When applying operations to Series, its really just matrix operations.
   However, when applying them to Series or Dataframes, note that python will match labels 
   before applying any operation to the values. For any labels that it cannot find a match,
   it will leave in place a null value"""

'When applying operations to Series, its really just matrix operations.\n   However, when applying them to Series or Dataframes, note that python will match labels \n   before applying any operation to the values. For any labels that it cannot find a match,\n   it will leave in place a null value'

In [62]:
ser1+ser2

GERMANY    4.0
ITALY      NaN
JAPAN      8.0
USA        2.0
USSR       NaN
dtype: float64

In [63]:
"""The following cells will focus on Dataframes, which will be the staple datatype
   used for analysis and machine learning."""

'The following cells will focus on Dataframes, which will be the staple datatype\n   used for analysis and machine learning.'

In [64]:
#Much of this is based off videos and notes, so the follwing random
#seed is one used in an example video.

from numpy.random import randn

In [65]:
np.random.seed(101)

In [66]:
df = pd.DataFrame(randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])

In [67]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [68]:
#Indexing a dataframe is done by the columns

df['W']

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [69]:
df[['W','X']]

W         X
A  2.706850  0.628133
B  0.651118 -0.319318
C -2.018168  0.740122
D  0.188695 -0.758872
E  0.190794  1.978757

In [70]:
#Creating a new column, especially if its based on data already in the column, 
#is done as if the column already exists.

df['NEW'] = df['W'] + df['X'] 

In [71]:
df

W         X         Y         Z       NEW
A  2.706850  0.628133  0.907969  0.503826  3.334983
B  0.651118 -0.319318 -0.848077  0.605965  0.331800
C -2.018168  0.740122  0.528813 -0.589001 -1.278046
D  0.188695 -0.758872 -0.933237  0.955057 -0.570177
E  0.190794  1.978757  2.605967  0.683509  2.169552

In [72]:
# removing a column is done by using the .drop method. However, if dropping information
# from the data as a permanent measure, then using the inplace parameter is necessary.

In [73]:
df.drop('NEW', axis=1, inplace=True)

In [74]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [75]:
#indexing can also be done with rows, however it is done with the aid of a method.

df.loc['A']

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [76]:
df.loc[['A','B']]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965

In [77]:
#An alternative .iloc[] can be used to index a row numerically, regardless of index label.

df.iloc[0]

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [78]:
#Indexing subsections of dataframes is done with .loc()
df.loc['B','Y']

-0.8480769834036315

In [79]:
df.loc[['A','B'],['W','Y']]

W         Y
A  2.706850  0.907969
B  0.651118 -0.848077

In [80]:
"""FOLLOWING WILL BE FURTHER DATAFRAME HANDLING"""

'FOLLOWING WILL BE FURTHER DATAFRAME HANDLING'

In [81]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [157]:
#Dataframes can also use  conditional indexing
booldf = df > 0
booldf

W      X      Y      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True
E   True   True   True   True

In [159]:
df[booldf]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [161]:
df[df>0]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [163]:
df[df['W']>0]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [165]:
#Just like normal indexing, conditionally indexed dataframes can themselves be
#indexed to further analyze.

resultsDF = df[df['W']>0]


In [167]:
resultsDF

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [169]:
resultsDF['X']

A    0.628133
B   -0.319318
D   -0.758872
E    1.978757
Name: X, dtype: float64

In [171]:
#This can also be done in one step.

df[df['W']>0]['X']

A    0.628133
B   -0.319318
D   -0.758872
E    1.978757
Name: X, dtype: float64

In [173]:
df[df['W']>0][['Y','X']]

Y         X
A  0.907969  0.628133
B -0.848077 -0.319318
D -0.933237 -0.758872
E  2.605967  1.978757

In [175]:
#ADDING MULTIPLE CONDITIONS REQUIRES THE USE OF THE & OPERATOR.
#This is because the normal 'and' operator runs into problems handling dataframes.

#Note you can use the pipe operator (|) in place of 'or'

df[(df['W']>0) & (df['Y']>1)]

W         X         Y         Z
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
"""THE FOLLOWING CELLS WILL LOOK INTO DATAFRAME INDEX (I.E.
   RESETTING INDICES, RENAMING)"""

In [177]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [179]:
#RESETTING THE INDEX.
#THIS ALSO REQUIRES THE CHANGE TO BE SPECIFIED AS 'INPLACE'

df.reset_index() #reindexing turns the original index into a new column

index         W         X         Y         Z
0     A  2.706850  0.628133  0.907969  0.503826
1     B  0.651118 -0.319318 -0.848077  0.605965
2     C -2.018168  0.740122  0.528813 -0.589001
3     D  0.188695 -0.758872 -0.933237  0.955057
4     E  0.190794  1.978757  2.605967  0.683509

In [181]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [185]:
#SETTING THE INDEX
newind = 'CA NY WY OR CO'.split()

In [187]:
newind

['CA', 'NY', 'WY', 'OR', 'CO']

In [189]:
df['States'] = newind

In [191]:
df

W         X         Y         Z States
A  2.706850  0.628133  0.907969  0.503826     CA
B  0.651118 -0.319318 -0.848077  0.605965     NY
C -2.018168  0.740122  0.528813 -0.589001     WY
D  0.188695 -0.758872 -0.933237  0.955057     OR
E  0.190794  1.978757  2.605967  0.683509     CO

In [193]:
df.set_index('States') #Requires an inplace assignment

W         X         Y         Z
States                                        
CA      2.706850  0.628133  0.907969  0.503826
NY      0.651118 -0.319318 -0.848077  0.605965
WY     -2.018168  0.740122  0.528813 -0.589001
OR      0.188695 -0.758872 -0.933237  0.955057
CO      0.190794  1.978757  2.605967  0.683509