In [9]:
"""This Notebook will run through the fundamentals of data analysis tools.
   From series and dataframes to basics in data analysis in Pandas and Seaborn. """

'This Notebook will run through the fundamentals of data analysis tools.\n   From series and dataframes to basics in data analysis in Pandas and Seaborn. '

In [10]:
#Following will be basic data types which will be ever present, and their common methods

In [11]:
my_list = ['a','b','c']

In [12]:
print(my_list)

['a', 'b', 'c']


In [13]:
my_list.append('New')

In [14]:
my_list.append(['d','e','f'])

In [15]:
my_list[4][1]

'e'

In [16]:
dict = {'key1':{'innerkey1':[0,1,2]}}

In [17]:
dict['key1']['innerkey1'][2]

2

In [18]:
dict['key1'] = [1,2,3]

In [19]:
dict['key2'] = [4,5,6]

In [20]:
if 1>2:
    print('wrong!')
else:
    print('learn better syntax')

learn better syntax


In [21]:
def times2(var):
    return var*2

In [22]:
seq = [1,2,3,4,5]

for num in seq:
    print(times2(num))

2
4
6
8
10


In [23]:
list(map(lambda num: num*3,seq))

[3, 6, 9, 12, 15]

In [24]:
list(filter(lambda num: num%2 == 0, seq))

[2, 4]

In [25]:
import numpy as np

In [26]:
#This will be followed by numpy excercises and notes 
my_list = [1,2,3]

np.array(my_list)



array([1, 2, 3])

In [27]:
arr = np.array(my_list)
print(arr)

[1 2 3]


In [28]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]] # A matrice is reperesented as a list of lists

In [29]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
#Generating lists can be done quickly with numpy

np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
np.zeros(3)

array([0., 0., 0.])

In [32]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [33]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [34]:
np.linspace(0,11,5) #Generates arrays filled with a number of evenly spaced values within a range

array([ 0.  ,  2.75,  5.5 ,  8.25, 11.  ])

In [35]:
np.random.rand(5)

array([0.84286423, 0.53996816, 0.94544588, 0.18473843, 0.80425857])

In [36]:
np.random.rand(5,5)

array([[0.22482996, 0.54587051, 0.58769397, 0.61003052, 0.45472895],
       [0.56103995, 0.41223063, 0.08110412, 0.50884824, 0.20933163],
       [0.93046346, 0.1986378 , 0.16018885, 0.79077548, 0.34789538],
       [0.5188637 , 0.15057445, 0.97638792, 0.71142941, 0.11127961],
       [0.9776631 , 0.16797144, 0.16346673, 0.47064916, 0.40253871]])

In [37]:
np.random.randn(5) # Gaussian distribution around 0

array([ 1.51893681, -0.29235332,  2.59339712, -0.04829072, -0.30758798])

In [38]:
arr = np.random.randint(1,100,10) #10 random integers between 1(incl) and 100(excl)

In [39]:
arr.max()

98

In [40]:
arr.argmax()

2

In [41]:
# what follows are notes and examples of numpy indexing and selection.

In [42]:
arr = np.arange(1,11)

In [43]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
arr[0:6]

array([1, 2, 3, 4, 5, 6])

In [45]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [46]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [47]:
arr_2d[:3,1:2]

array([[10],
       [25],
       [40]])

In [48]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [50]:
bool_arr = arr > 5

In [51]:
#Following will be Pandas basics from series to dataframes

In [52]:
import numpy as np
import pandas as pd

In [53]:
labels = ['a','b','c']
my_data = [10,20,30]
arr = np.array(my_data)
dic = {'a':10,'b':20,'c':30}

In [54]:
pd.Series(data=my_data, index=labels)

a    10
b    20
c    30
dtype: int64

In [55]:
#Raw lists can be used to create pandas series along with numpy arrays as well.
pd.Series(arr,labels)

a    10
b    20
c    30
dtype: int32

In [56]:
"""Note that passing in a dictionary will have the keys be assigned as indices
    and the values will be assigned as data."""

pd.Series(dic)

a    10
b    20
c    30
dtype: int64

In [57]:
# Series, just like a dictionary, make it easier to look up information more precisely.
# Following is an example

In [58]:
ser1 = pd.Series([1,2,3,4], ['USA','GERMANY','USSR','JAPAN'])
ser1

USA        1
GERMANY    2
USSR       3
JAPAN      4
dtype: int64

In [59]:
ser2 = pd.Series([1,2,5,4], ['USA','GERMANY','ITALY','JAPAN'])
ser2

USA        1
GERMANY    2
ITALY      5
JAPAN      4
dtype: int64

In [60]:
#Grabbing information is similar to indexing

ser1['USA']

1

In [61]:
"""When applying operations to Series, its really just matrix operations.
   However, when applying them to Series or Dataframes, note that python will match labels 
   before applying any operation to the values. For any labels that it cannot find a match,
   it will leave in place a null value"""

'When applying operations to Series, its really just matrix operations.\n   However, when applying them to Series or Dataframes, note that python will match labels \n   before applying any operation to the values. For any labels that it cannot find a match,\n   it will leave in place a null value'

In [62]:
ser1+ser2

GERMANY    4.0
ITALY      NaN
JAPAN      8.0
USA        2.0
USSR       NaN
dtype: float64

In [118]:
"""The following cells will focus on Dataframes, which will be the staple datatype
   used for analysis and machine learning."""

'The following cells will focus on Dataframes, which will be the staple datatype\n   used for analysis and machine learning.'

In [120]:
#Much of this is based off videos and notes, so the follwing random
#seed is one used in an example video.

from numpy.random import randn

In [122]:
np.random.seed(101)

In [124]:
df = pd.DataFrame(randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])

In [126]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [138]:
#Indexing a dataframe is done by the columns

df['W']

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [162]:
df[['W','X']]

W         X
A  2.706850  0.628133
B  0.651118 -0.319318
C -2.018168  0.740122
D  0.188695 -0.758872
E  0.190794  1.978757

In [164]:
#Creating a new column, especially if its based on data already in the column, 
#is done as if the column already exists.

df['NEW'] = df['W'] + df['X'] 

In [166]:
df

W         X         Y         Z       NEW
A  2.706850  0.628133  0.907969  0.503826  3.334983
B  0.651118 -0.319318 -0.848077  0.605965  0.331800
C -2.018168  0.740122  0.528813 -0.589001 -1.278046
D  0.188695 -0.758872 -0.933237  0.955057 -0.570177
E  0.190794  1.978757  2.605967  0.683509  2.169552

In [168]:
# removing a column is done by using the .drop method. However, if dropping information
# from the data as a permanent measure, then using the inplace parameter is necessary.

In [170]:
df.drop('NEW', axis=1, inplace=True)

In [172]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [178]:
#indexing can also be done with rows, however it is done with the aid of a method.

df.loc['A']

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [180]:
df.loc[['A','B']]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965

In [182]:
#An alternative .iloc[] can be used to index a row numerically, regardless of index label.

df.iloc[0]

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [184]:
#Indexing subsections of dataframes is done with .loc()
df.loc['B','Y']

-0.8480769834036315

In [186]:
df.loc[['A','B'],['W','Y']]

W         Y
A  2.706850  0.907969
B  0.651118 -0.848077