In [ ]:
"""This Notebook will run through the fundamentals of data analysis tools.
   From series and dataframes to basics in data analysis in Pandas and Seaborn. """

In [ ]:
#Following will be basic data types which will be ever present, and their common methods

In [1]:
my_list = ['a','b','c']

In [3]:
print(my_list)

['a', 'b', 'c']


In [5]:
my_list.append('New')

In [13]:
my_list.append(['d','e','f'])

In [17]:
my_list[4][1]

'e'

In [35]:
dict = {'key1':{'innerkey1':[0,1,2]}}

In [37]:
dict['key1']['innerkey1'][2]

2

In [45]:
dict['key1'] = [1,2,3]

In [49]:
dict['key2'] = [4,5,6]

In [61]:
if 1>2:
    print('wrong!')
else:
    print('learn better syntax')

learn better syntax


In [63]:
def times2(var):
    return var*2

In [69]:
seq = [1,2,3,4,5]

for num in seq:
    print(times2(num))

2
4
6
8
10


In [73]:
list(map(lambda num: num*3,seq))

[3, 6, 9, 12, 15]

In [75]:
list(filter(lambda num: num%2 == 0, seq))

[2, 4]

In [1]:
import numpy as np

In [3]:
#This will be followed by numpy excercises and notes 
my_list = [1,2,3]

np.array(my_list)



array([1, 2, 3])

In [5]:
arr = np.array(my_list)
print(arr)

[1 2 3]


In [7]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]] # A matrice is reperesented as a list of lists

In [9]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
#Generating lists can be done quickly with numpy

np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.linspace(0,11,5) #Generates arrays filled with a number of evenly spaced values within a range

array([ 0.  ,  2.75,  5.5 ,  8.25, 11.  ])

In [21]:
np.random.rand(5)

array([0.55682002, 0.43141368, 0.6549408 , 0.00456605, 0.42125784])

In [23]:
np.random.rand(5,5)

array([[0.49586205, 0.51315164, 0.92059415, 0.02605299, 0.33786377],
       [0.30576336, 0.14368624, 0.5110927 , 0.96864978, 0.51527577],
       [0.11005202, 0.50769365, 0.29860259, 0.36418549, 0.53926703],
       [0.05115817, 0.15171045, 0.14117049, 0.29140579, 0.46062856],
       [0.85856338, 0.02081879, 0.85923699, 0.68515004, 0.57700425]])

In [25]:
np.random.randn(5) # Gaussian distribution around 0

array([-1.91618903, -0.58674354, -0.02936219,  1.37065708,  0.35317586])

In [29]:
arr = np.random.randint(1,100,10) #10 random integers between 1(incl) and 100(excl)

In [31]:
arr.max()

85

In [35]:
arr.argmax()

6

In [ ]:
# what follows are notes and examples of numpy indexing and selection.

In [43]:
arr = np.arange(1,11)

In [45]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
arr[0:6]

array([1, 2, 3, 4, 5, 6])

In [63]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [73]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [95]:
arr_2d[:3,1:2]

array([[10],
       [25],
       [40]])

In [97]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [99]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [101]:
bool_arr = arr > 5

In [1]:
#Following will be Pandas basics from series to dataframes

In [3]:
import numpy as np
import pandas as pd

In [5]:
labels = ['a','b','c']
my_data = [10,20,30]
arr = np.array(my_data)
dic = {'a':10,'b':20,'c':30}

In [9]:
pd.Series(data=my_data, index=labels)

a    10
b    20
c    30
dtype: int64

In [11]:
#Raw lists can be used to create pandas series along with numpy arrays as well.
pd.Series(arr,labels)

a    10
b    20
c    30
dtype: int32

In [13]:
"""Note that passing in a dictionary will have the keys be assigned as indices
    and the values will be assigned as data."""

pd.Series(dic)

a    10
b    20
c    30
dtype: int64

In [15]:
# Series, just like a dictionary, make it easier to look up information more precisely.
# Following is an example

In [17]:
ser1 = pd.Series([1,2,3,4], ['USA','GERMANY','USSR','JAPAN'])
ser1

USA        1
GERMANY    2
USSR       3
JAPAN      4
dtype: int64

In [20]:
ser2 = pd.Series([1,2,5,4], ['USA','GERMANY','ITALY','JAPAN'])
ser2

USA        1
GERMANY    2
ITALY      5
JAPAN      4
dtype: int64

In [22]:
#Grabbing information is similar to indexing

ser1['USA']

1